services:
  - type: web
    name: futeiz-portfolio
    runtime: static
    buildCommand: npm run build
    staticPublishPath: ./export-build
    envVars:
      - key: NODE_VERSION
        value: 20
    routes:
      - type: rewrite
        source: /*
        destination: /index.html